# https://starship.rs/config/

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$directory\

$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\

$shell\
$character\
"""

right_format = """
$nodejs\
$python\

$cmd_duration\
"""

add_newline = false

[directory]
fish_style_pwd_dir_length = 1

[nodejs]
# trigger this module only with files or folders
detect_extensions = []

[python]
symbol = "󰌠 "
# trigger this module only with files
detect_extensions = []

[shell]
fish_indicator = "fish "
zsh_indicator = ""
format = "[$indicator]($style)"
disabled = false
