# https://starship.rs/config/

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$directory\

$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\

$character\
"""

add_newline = false

[directory]
fish_style_pwd_dir_length = 1
